In [1]:
import numpy as np

# 1. Create a null vector of size 10 but the fifth value which is 1.

In [2]:
x=np.zeros(10)
x[4]=1
print('The null vector is :',x)

The null vector is : [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


# 2. Create a vector with values ranging from 10 to 49

In [3]:
x=np.arange(10,50)
print('The vector is :',x)

The vector is : [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


# 3. Create a 3x3 matrix with values ranging from 0 to 8

In [4]:
x=np.arange(0,9).reshape(3,3)
print('A 3*3 matrix is :\n',x)

A 3*3 matrix is :
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


# 4. Find indices of non-zero elements from [1,2,0,0,4,0]

In [5]:
a=np.array([1,2,0,0,4,0])
print(np.nonzero(a))

(array([0, 1, 4], dtype=int64),)


# 5. Create a 10x10 array with random values and find the minimum and maximum values.

In [6]:
x = np.random.random((10,10))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum Value is :",xmin)
print('Maximum Value is :',xmax)

Original Array:
[[0.19655716 0.56039109 0.21291938 0.32878739 0.98548122 0.63028286
  0.95885371 0.80103575 0.69841247 0.0650007 ]
 [0.18209437 0.02252294 0.187928   0.9942018  0.31568949 0.63777741
  0.08559739 0.45636493 0.80717009 0.15507359]
 [0.04594799 0.02176547 0.95305424 0.09209359 0.59396871 0.75646529
  0.90873623 0.87324047 0.60547344 0.93242724]
 [0.65231873 0.12767562 0.19160056 0.53028778 0.57178054 0.7118506
  0.19521257 0.55943172 0.58154604 0.92103598]
 [0.83662957 0.42713635 0.87934258 0.37168145 0.35488416 0.40150534
  0.34791443 0.58384773 0.84247255 0.24811928]
 [0.7680395  0.52332254 0.63758052 0.31965922 0.02250319 0.68373706
  0.94213317 0.52418168 0.84536749 0.95502421]
 [0.15076463 0.08620007 0.79099897 0.32484846 0.80950435 0.62514703
  0.35463494 0.58703505 0.67441493 0.18983421]
 [0.83953958 0.73191249 0.73258649 0.15490486 0.13157237 0.07655052
  0.04340507 0.51360007 0.9343542  0.64519397]
 [0.04209532 0.20349075 0.14092401 0.75575751 0.69592296 0.499183

# 6. Create a random vector of size 30 and find the mean value.

In [7]:
x=np.random.random(30)
y=x.mean()
print('The mean value is :',y)

The mean value is : 0.46523451644150143
